version: "3.8"
volumes:
  psql:
services:
  api-app:
    restart: always
    build:
      context: ../../
      dockerfile: ./Docker/dev/Dockerfile
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db-app
    volumes:
      - ../../src:/usr/src/app
    tty: true
    stdin_open: true
  db-app:
    image: postgres
    env_file:
      - ./.postgres.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - psql:/var/lib/postgresql/data
